### ISSUE TITLE
Create Print Preview Menu Item and Functionality

### ISSUE THREAD

**Issue by smudger** [5mudg3r/Rota-Manager-JavaFX-#6]
This should give the user the ability to edit the week's shopping list by adding and removing items before printing.

**Comment by smudger** [comment]
Functionality added in dev branch, needs testing regarding actual printing before merge to master

**Comment by smudger** [comment]
Implemented into main release in commit 139af41
Be sure to use `git pull` before programming so that you have these changes @Rhatty59

**Comment by Rhatty59** [comment]
Nice. I'll pull it down this afternoon

Regards, Dad
